version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
    command: npm run back:dev
    volumes:
      - .:/app
    ports:
      - "4040:4040"
  app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run front:dev
    volumes:
      - .:/app
    ports:
      - "9000:9000"
